# Generated by Django 4.2 on 2026-04-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_rename_ultima_modificacion_por_configuracionsistema_ultima_modificacion_por_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='tolerancia_minutos',
            field=models.IntegerField(default=30),
        ),
    ]
