# Generated by Django 4.2 on 2026-06-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_configuracionsistema_geocerca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='geocerca_auditoria',
            field=models.BooleanField(default=True, help_text='Registra en auditoría los detalles de cada validación de geocerca.'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='geocerca_obligatoria',
            field=models.BooleanField(default=True, help_text='Si True y la geocerca está activa: si el usuario deniega permisos de geolocalización, la marcación es rechazada.'),
        ),
    ]
