# Generated by Django 4.2 on 2026-03-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacion',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marcacion',
            name='ip_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='marcacion',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marcacion',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marcacion',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
