# Generated by Django 4.2 on 2026-04-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcaciones', '0002_marcacion_ciudad_marcacion_ip_info_marcacion_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacion',
            name='va_a_asistencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='marcacion',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA_VALIDA', 'Entrada válida'), ('SALIDA_VALIDA', 'Salida válida'), ('FUERA_HORARIO', 'Fuera de horario'), ('SOLO_VERIFICACION', 'Solo verificación (día no laborable)'), ('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=20),
        ),
    ]
